---
- name: Build YML File
  hosts: localhost
  connection: local
  vars_files: 
    - aws_inventory_sources.yml
    - main.yml

  tasks:

    # - name: Git checkout
    #   ansible.builtin.git:
    #     repo: "{{ git_repo }}"
    #     dest: "{{ playbook_dir }}"
    #     version: main
      #  version: "aig_inventory_update_{{ ansible_date_time.iso8601_basic_short }}"

    - ansible.builtin.debug: var=playbook_dir

  
    - ansible.builtin.set_fact:
         git_branch: "aig_inventory_update_{{ ansible_date_time.iso8601_basic_short }}"


    - name: Create new branch
      ansible.builtin.shell: "git checkout -b {{ git_branch }}"
      args:
         chdir: "{{ playbook_dir }}"

    - name: current branch
      ansible.builtin.shell: "git branch"
      args:
         chdir: "{{ playbook_dir }}"

    - name: Create new branch
      ansible.builtin.shell: "git status"
      args:
         chdir: "{{ playbook_dir }}"
      register: status

    - ansible.builtin.debug: var=playbook_dir


    # - name: Set facts
    #   ansible.builtin.set_fact:
    #     var2:
    #       - 511309077648
    #       - 311331131131

    # - name: Copy Content
    #   ansible.builtin.blockinfile:
    #     path: vars/aws_inventory_sources.yml
    #     block: "{{ var2 | to_nice_yaml }}"
    #     insertafter: "aig_accounts"
    #     mode: "0755"

    # - name: Build Inventory Sources
    #   ansible.builtin.template:
    #      src: aws_ec2.yml.j2
    #      dest: inventory/aig_{{ aws_account }}_aws_ec2.yml
    #   loop_control:
    #      loop_var: aws_account
    #   loop: "{{aig_aws_accounts}}"


