---
- name: Build And Push Inventory Sources
  hosts: localhost
  connection: local
  vars_files:
    - aws_inventory_sources.yml
    - main.yml

  tasks:

    - name: Clone AWS Inventory Repo
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ git_working_directory }}"
        clone: true
        update: true
        version: main

    - name: Create Branch
      ansible.builtin.set_fact:
        git_develop_branch: "aig_inventory_update_{{ ansible_date_time.iso8601_basic_short }}"

    - name: Create a new branch with current timestamp
      ansible.builtin.shell: "git checkout -b {{ git_develop_branch }}"
      args:
        chdir: "{{ git_working_directory }}"

    - name: Create temporary list of accounts. The aws list-accounts will replace this when we get access.
      ansible.builtin.set_fact:
        aws_accounts_list:
          - 511309077648
          - 969289287447
          - 454534930493

    - name: Copy Content
      ansible.builtin.blockinfile:
        path: vars/aws_inventory_sources.yml
        block: "{{ aws_accounts_list | to_nice_yaml }}"
        insertafter: "aig_accounts"
        mode: "0755"

    - name: Build Inventory Sources
      ansible.builtin.template:
        src: aws_ec2.yml.j2
        dest: inventory/aig_{{ aws_account }}.aws_ec2.yml
        mode: "0755"
      loop_control:
        loop_var: aws_account
      loop: "{{ aig_aws_accounts }}"

    - name: Copy generated inventory and aws inventory sources master list to git working directory
      ansible.builtin.copy:
        dest: "{{ git_working_directory }}"
        src: "{{ item }}"
        force: true
        mode: "0755"
      loop:
        - "{{ playbook_dir }}/inventory"
        - "{{ playbook_dir }}/vars"

    - name: "Commit Inventory Changes"
      ansible.builtin.shell: |
        git config --global user.name "rhaap"
        git config --global user.email "rhaap@rhaap.com"
        git add -A && git commit -m "RHAAP Job ID {{ tower_job_id }}: Automated Commit by Ansible" 
      args:
        chdir: "{{ git_working_directory }}"
      ignore_errors: true
      register: output
      failed_when: >
        output.msg != "" and
        ("error" in output.msg or
        "conflict" in output.msg or
        "Errno" in output.msg or
        "fatal" in output.msg or
        (output.stdout != "" and
        "nothing to commit, working tree clean" not in output.stdout) or
        (output.stderr != ""))

    - name: Set remote url
      ansible.builtin.shell: "git remote set-url origin https://{{ git_username }}:{{ git_token }}@github.com/{{ git_username }}/{{ github_reponame }}.git"
      args:
        chdir: "{{ git_working_directory }}"
      no_log: true

    - name: Push Changes
      ansible.builtin.shell: "git push --set-upstream origin {{ git_develop_branch }} --force"
      args:
        chdir: "{{ git_working_directory }}"
      register: push_output

    - name: Create pull request
      ansible.builtin.uri:
        method: POST
        headers:
          Accept: "application/vnd.github+json"
          Authorization: "Bearer {{ git_token }}"
        url: "{{ github_api_url }}"
        body:
          title: "AWS Inventory Changes - {{ ansible_date_time }}"
          head: "{{ git_username }}:{{ git_develop_branch }}"
          base: "{{ git_base_branch }}"
        body_format: json
        validate_certs: false
        status_code: [200, 201, 422]
      changed_when:
        - (pull_request_results.status == 201) or (pull_request_results.status == 200)
      register: pull_request_results

    - name: Debug custom_exported_data
      ansible.builtin.debug:
        msg:
          - "SUCCESS: HTTP Status - {{ pull_request_results.status }}"
      when:
        - (ansible_verbosity <= 3)
        - (ansible_verbosity >= 1)
        - (pull_request_results.status == 201) or (pull_request_results.status == 200) or (pull_request_results.status == 422)
