---
- hosts: all
  name: Import AAP config
  connection: local

  collections:
    - ansible.controller

  roles:
    - {role: infra.controller_configuration.credential_types, when: controller_credential_types is defined}
    - {role: infra.controller_configuration.job_templates, when: controller_templates is defined}


  pre_tasks:
    - name: set fact on the configs directory
      ansible.builtin.set_fact: 
        config_path: "{{ playbook_dir }}/configurations"

    - name: Include configurations from configurations' directory
      include_vars:
        dir: "{{ config_path }}" 
        extensions: ["yml","json"]
      register: config_files

  tasks:

  - name: Current version of ansible controller 
    ansible.builtin.shell: ansible-galaxy collection list

  

  # - name: Import Assets
  #   ansible.controller.import: 
  #     assets: "{{ config_files.ansible_facts | from_yaml | to_json }}" 
  #     validate_certs: False
  #   register: import_results