---
plugin: aws_ec2

regions:
  - us-east-2
  
iam_role_arn: "arn:aws:iam::404388677917:role/ansible-role"

groups:
  windows: (platform_details is defined and platform_details == 'Windows')
  linux: (platform_details is defined and platform_details == 'Linux')

# keyed_groups may be used to create custom groups
strict: False
keyed_groups:
 #  - key: platform_details



filters:
   
