---
plugin: aws_ec2

regions:
  - us-east-1
  
iam_role_arn: "arn:aws:iam::349394834233:role/ansible-role"


# keyed_groups may be used to create custom groups
strict: False
keyed_groups:



filters:
   
